use pest::Parser;
use pest_derive::Parser;
use std::{env, fs};

#[derive(Parser)]
#[grammar = "nephilim.pest"]
pub struct NephilimParser;

fn main() {
    let spec_path = env::args().nth(1).unwrap_or("../nephilim.spec".to_string());
    let spec = fs::read_to_string(&spec_path).expect("spec file missing");
    
    let pairs = NephilimParser::parse(Rule::manifold, &spec).expect("parse failed");
    println!("✓ Parsed {}", spec_path);
    
    let mut out = String::from("// AUTO-GENERATED by nephilimc\n");
    for pair in pairs {
        for inner in pair.into_inner() {
            if inner.as_rule() == Rule::section {
                let section_name = inner.as_str().split_whitespace().next().unwrap_or("");
                for kv in inner.into_inner() {
                    if kv.as_rule() == Rule::pair_list {
                        for p in kv.into_inner() {
                            let mut it = p.into_inner();
                            let k = it.next().unwrap().as_str();
                            let v = it.next().unwrap().as_str().trim();
                            let v_clean = v.split_whitespace().next().unwrap();
                            out += &format!("pub const {}_{}: &str = \"{}\";\n", 
                                section_name.to_uppercase(), k.to_uppercase(), v_clean);
                        }
                    }
                }
            }
        }
    }
    fs::write("../core/src/generated.rs", out).unwrap();
    println!("✓ generated ../core/src/generated.rs");
}
